# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
favicon: /image/favicon.ico

# Content
excerpt_link: Read More

# Comment
# Disqus
disqus_shortname: 

# baidu site verification content
baidu_site: 
# baidu tongji (the string after "hm.js?")
baidu_tongji: 

# fontawesome_url (or path to fontawesome 4.x)
fontawesome_url: https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css